import { db } from '@/db';
import { tasks } from '@/db/schema';

async function main() {
    const now = new Date();
    const currentTimestamp = now.toISOString();
    
    const sampleTasks = [
        {
            institutionId: 1,
            title: 'Design new social media campaign',
            description: 'Create engaging visual designs and content strategy for upcoming Q2 social media campaign across all platforms including Facebook, Instagram, and LinkedIn.',
            status: 'in_progress',
            priority: 'high',
            assignedToId: 3,
            createdById: 1,
            dueDate: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Update website content',
            description: 'Review and update all website pages with latest product information, testimonials, and company achievements. Ensure all links are working properly.',
            status: 'todo',
            priority: 'medium',
            assignedToId: 4,
            createdById: 1,
            dueDate: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Create video content for Instagram',
            description: 'Produce short-form video content showcasing behind-the-scenes of our creative process. Target 3-5 reels for the week with trending audio.',
            status: 'in_progress',
            priority: 'urgent',
            assignedToId: 5,
            createdById: 2,
            dueDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Schedule client meetings',
            description: 'Coordinate and schedule quarterly review meetings with all active clients. Send calendar invites and prepare meeting agendas.',
            status: 'done',
            priority: 'high',
            assignedToId: 3,
            createdById: 1,
            dueDate: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Review analytics reports',
            description: 'Analyze website traffic, social media engagement metrics, and campaign performance data. Prepare summary report with actionable insights.',
            status: 'review',
            priority: 'medium',
            assignedToId: 4,
            createdById: 2,
            dueDate: new Date(now.getTime() + 1 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Prepare monthly newsletter',
            description: 'Compile company updates, blog highlights, and upcoming events into engaging newsletter format. Coordinate with team for content contributions.',
            status: 'todo',
            priority: 'low',
            assignedToId: 5,
            createdById: 1,
            dueDate: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Update brand guidelines',
            description: 'Revise brand guidelines document to include new color palette, typography standards, and logo usage rules. Ensure consistency across all materials.',
            status: 'in_progress',
            priority: 'medium',
            assignedToId: 3,
            createdById: 2,
            dueDate: new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Photography for new products',
            description: 'Schedule and conduct professional product photography session for new inventory. Capture multiple angles and lifestyle shots for marketing use.',
            status: 'todo',
            priority: 'high',
            assignedToId: null,
            createdById: 6,
            dueDate: new Date(now.getTime() + 6 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Edit promotional video',
            description: 'Complete final edits on promotional video including color grading, audio mixing, and motion graphics. Prepare versions for different platforms.',
            status: 'review',
            priority: 'urgent',
            assignedToId: 5,
            createdById: 1,
            dueDate: new Date(now.getTime() + 1 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Social media audit',
            description: 'Conduct comprehensive audit of all social media channels including content performance, follower demographics, and engagement patterns.',
            status: 'done',
            priority: 'low',
            assignedToId: 4,
            createdById: 2,
            dueDate: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Create content calendar',
            description: 'Develop comprehensive content calendar for next quarter including blog posts, social media updates, and email campaigns with strategic themes.',
            status: 'in_progress',
            priority: 'high',
            assignedToId: 3,
            createdById: 1,
            dueDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Design email templates',
            description: 'Create responsive email templates for various campaigns including welcome series, promotional emails, and automated follow-ups.',
            status: 'todo',
            priority: 'medium',
            assignedToId: 4,
            createdById: 2,
            dueDate: new Date(now.getTime() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Competitor analysis research',
            description: 'Research and analyze competitor marketing strategies, content approaches, and social media presence. Identify opportunities and threats.',
            status: 'review',
            priority: 'low',
            assignedToId: 5,
            createdById: 1,
            dueDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Logo redesign project',
            description: 'Initiate logo redesign project with focus on modern aesthetics while maintaining brand recognition. Prepare multiple concept variations.',
            status: 'todo',
            priority: 'urgent',
            assignedToId: null,
            createdById: 7,
            dueDate: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            institutionId: 1,
            title: 'Website SEO optimization',
            description: 'Implement SEO best practices including meta tags optimization, keyword research, internal linking structure, and page speed improvements.',
            status: 'done',
            priority: 'high',
            assignedToId: 3,
            createdById: 2,
            dueDate: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    await db.insert(tasks).values(sampleTasks);
    
    console.log('✅ Tasks seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});